version: "3.7"
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "database:/var/lib/postgresql/data"

volumes:
  database:
