# Generated by Django 3.0.3 on 2020-03-09 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator_set', related_query_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_set', related_query_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.Queue'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='resolver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolver_set', related_query_name='resolver', to=settings.AUTH_USER_MODEL),
        ),
    ]
