# Generated by Django 3.0.4 on 2020-03-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_update_related_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='ended',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
