# Generated by Django 3.0.4 on 2020-03-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20200315_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='resolution',
            field=models.TextField(blank=True),
        ),
    ]
