# Generated by Django 3.0.4 on 2020-03-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20200315_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Subject'),
        ),
    ]
