# Generated by Django 3.0.4 on 2020-03-18 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20200315_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'permissions': [('work_incident', 'Can work incidents')]},
        ),
    ]
