# Generated by Django 3.0.4 on 2020-03-18 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20200318_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'permissions': [('work_incident', 'Can work incident')]},
        ),
    ]
