# Generated by Django 3.0.4 on 2020-03-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20200318_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('SM', 'Submitted'), ('EQ', 'Enqueued'), ('AS', 'Assigned'), ('RS', 'Resolved'), ('CL', 'Closed'), ('RO', 'Reopened')], default='SM', max_length=2),
        ),
    ]
