# Generated by Django 3.0.4 on 2020-03-15 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, null=True, unique=True)),
                ('street', models.CharField(blank=True, max_length=512, verbose_name='Street Address')),
                ('post_office_box', models.CharField(blank=True, max_length=256, verbose_name='PO Box')),
                ('city', models.CharField(blank=True, max_length=256)),
                ('state', models.CharField(blank=True, max_length=256, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('middle_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
                ('office', models.CharField(blank=True, max_length=256)),
                ('phone_number', models.CharField(blank=True, max_length=256)),
                ('mobile_number', models.CharField(blank=True, max_length=256)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('identifier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
