# Generated by Django 3.0.4 on 2020-03-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_auto_20200315_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
